### ISSUE TITLE
SQL Error on Docker Run

### ISSUE THREAD

**Issue by stvhanna** [ankane/blazer-docker#1]
@ankane Thanks for quickly putting this together! I'm happy to test and give feedback.

After running `docker run -ti -e DATABASE_URL=postgres://user:password@hostname:5432/dbname -p 8080:8080 blazer` with the actual target database info, I get an error:

```
[1] Puma starting in cluster mode...
[1] * Version 4.3.1 (ruby 2.6.5-p114), codename: Mysterious Traveller
[1] * Min threads: 1, max threads: 16
[1] * Environment: production
[1] * Process workers: 3
[1] * Preloading application
[1] * Listening on tcp://0.0.0.0:8080
[1] ! WARNING: Detected 1 Thread(s) started in app boot:
[1] ! #<Thread:0x0000559908b797a0@/usr/local/bundle/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:336 sleep> - /usr/local/bundle/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:339:in `sleep'
[1] Use Ctrl-C to stop
[1] - Worker 0 (pid: 8) booted, phase: 0
[1] - Worker 2 (pid: 15) booted, phase: 0
[1] - Worker 1 (pid: 10) booted, phase: 0
Started GET "/" for 172.17.0.1 at 2020-02-05 22:09:16 +0000
Processing by Blazer::QueriesController#home as HTML
Completed 500 Internal Server Error in 1147ms (ActiveRecord: 444.0ms | Allocations: 3772)
  
ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "blazer_queries" does not exist
LINE 8:  WHERE a.attrelid = '"blazer_queries"'::regclass
                            ^
):
  
activerecord (6.0.2.1) lib/active_record/connection_adapters/postgresql/database_statements.rb:65:in `exec'
activerecord (6.0.2.1) lib/active_record/connection_adapters/postgresql/database_statements.rb:65:in `block (2 levels) in query'
activesupport (6.0.2.1) lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
activesupport (6.0.2.1) lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
activesupport (6.0.2.1) lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
activerecord (6.0.2.1) lib/active_record/connection_adapters/postgresql/database_statements.rb:64:in `block in query'
activerecord (6.0.2.1) lib/active_record/connection_adapters/abstract_adapter.rb:718:in `block (2 levels) in log'
/usr/local/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
activerecord (6.0.2.1) lib/active_record/connection_adapters/abstract_adapter.rb:717:in `block in log'
activesupport (6.0.2.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activerecord (6.0.2.1) lib/active_record/connection_adapters/abstract_adapter.rb:708:in `log'
activerecord (6.0.2.1) lib/active_record/connection_adapters/postgresql/database_statements.rb:63:in `query'
activerecord (6.0.2.1) lib/active_record/connection_adapters/postgresql_adapter.rb:817:in `column_definitions'
activerecord (6.0.2.1) lib/active_record/connection_adapters/abstract/schema_statements.rb:114:in `columns'
activerecord (6.0.2.1) lib/active_record/connection_adapters/schema_cache.rb:76:in `columns'
activerecord (6.0.2.1) lib/active_record/connection_adapters/schema_cache.rb:82:in `columns_hash'
activerecord (6.0.2.1) lib/active_record/model_schema.rb:490:in `load_schema!'
activerecord (6.0.2.1) lib/active_record/attributes.rb:247:in `load_schema!'
activerecord (6.0.2.1) lib/active_record/attribute_decorators.rb:51:in `load_schema!'
activerecord (6.0.2.1) lib/active_record/model_schema.rb:480:in `block in load_schema'
/usr/local/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
activerecord (6.0.2.1) lib/active_record/model_schema.rb:477:in `load_schema'
activerecord (6.0.2.1) lib/active_record/model_schema.rb:352:in `columns_hash'
activerecord (6.0.2.1) lib/active_record/relation/query_methods.rb:1216:in `arel_column'
activerecord (6.0.2.1) lib/active_record/relation/query_methods.rb:1326:in `order_column'
activerecord (6.0.2.1) lib/active_record/relation/query_methods.rb:1309:in `block in preprocess_order_args'
activerecord (6.0.2.1) lib/active_record/relation/query_methods.rb:1306:in `map!'
activerecord (6.0.2.1) lib/active_record/relation/query_methods.rb:1306:in `preprocess_order_args'
activerecord (6.0.2.1) lib/active_record/relation/query_methods.rb:364:in `order!'
activerecord (6.0.2.1) lib/active_record/relation/query_methods.rb:359:in `order'
blazer (2.2.1) app/controllers/blazer/queries_controller.rb:280:in `set_queries'
blazer (2.2.1) app/controllers/blazer/queries_controller.rb:7:in `home'
actionpack (6.0.2.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (6.0.2.1) lib/abstract_controller/base.rb:196:in `process_action'
actionpack (6.0.2.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (6.0.2.1) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (6.0.2.1) lib/active_support/callbacks.rb:135:in `run_callbacks'
actionpack (6.0.2.1) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (6.0.2.1) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (6.0.2.1) lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
activesupport (6.0.2.1) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.2.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.2.1) lib/active_support/notifications.rb:180:in `instrument'
actionpack (6.0.2.1) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (6.0.2.1) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
activerecord (6.0.2.1) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
actionpack (6.0.2.1) lib/abstract_controller/base.rb:136:in `process'
actionview (6.0.2.1) lib/action_view/rendering.rb:39:in `process'
actionpack (6.0.2.1) lib/action_controller/metal.rb:191:in `dispatch'
actionpack (6.0.2.1) lib/action_controller/metal.rb:252:in `dispatch'
actionpack (6.0.2.1) lib/action_dispatch/routing/route_set.rb:51:in `dispatch'
actionpack (6.0.2.1) lib/action_dispatch/routing/route_set.rb:33:in `serve'
actionpack (6.0.2.1) lib/action_dispatch/journey/router.rb:49:in `block in serve'
actionpack (6.0.2.1) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.0.2.1) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.0.2.1) lib/action_dispatch/routing/route_set.rb:837:in `call'
railties (6.0.2.1) lib/rails/engine.rb:526:in `call'
railties (6.0.2.1) lib/rails/railtie.rb:190:in `public_send'
railties (6.0.2.1) lib/rails/railtie.rb:190:in `method_missing'
actionpack (6.0.2.1) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
actionpack (6.0.2.1) lib/action_dispatch/routing/mapper.rb:48:in `serve'
actionpack (6.0.2.1) lib/action_dispatch/journey/router.rb:49:in `block in serve'
actionpack (6.0.2.1) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.0.2.1) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.0.2.1) lib/action_dispatch/routing/route_set.rb:837:in `call'
rack (2.1.2) lib/rack/tempfile_reaper.rb:17:in `call'
rack (2.1.2) lib/rack/etag.rb:27:in `call'
rack (2.1.2) lib/rack/conditional_get.rb:27:in `call'
rack (2.1.2) lib/rack/head.rb:14:in `call'
actionpack (6.0.2.1) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.1.2) lib/rack/session/abstract/id.rb:269:in `context'
rack (2.1.2) lib/rack/session/abstract/id.rb:263:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/cookies.rb:648:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.2.1) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.2.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.2.1) lib/rails/rack/logger.rb:38:in `call_app'
railties (6.0.2.1) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.2.1) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.2.1) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.2.1) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.2.1) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.1.2) lib/rack/method_override.rb:24:in `call'
rack (2.1.2) lib/rack/runtime.rb:24:in `call'
activesupport (6.0.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.1.2) lib/rack/sendfile.rb:113:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/host_authorization.rb:77:in `call'
railties (6.0.2.1) lib/rails/engine.rb:526:in `call'
rack (2.1.2) lib/rack/urlmap.rb:77:in `block in call'
rack (2.1.2) lib/rack/urlmap.rb:61:in `each'
rack (2.1.2) lib/rack/urlmap.rb:61:in `call'
puma (4.3.1) lib/puma/configuration.rb:228:in `call'
puma (4.3.1) lib/puma/server.rb:681:in `handle_request'
puma (4.3.1) lib/puma/server.rb:472:in `process_client'
puma (4.3.1) lib/puma/server.rb:328:in `block in run'
puma (4.3.1) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```

**Comment by ankane** [comment]
Added instructions for how to create the database tables. You'll need to pull and rebuild the Docker image.
