### ISSUE TITLE
Puma error when trying to run docker image

### ISSUE THREAD

**Issue by jshthornton** [ankane/blazer-docker#11]
```
/app/config/puma.rb:6:in `_load_from': uninitialized constant #<Class:#<Puma::DSL:0x0000004005e54b48>>::DefaultRackup (NameError)
        from /usr/local/bundle/gems/puma-6.1.1/lib/puma/dsl.rb:132:in `instance_eval'
        from /usr/local/bundle/gems/puma-6.1.1/lib/puma/dsl.rb:132:in `_load_from'
        from /usr/local/bundle/gems/puma-6.1.1/lib/puma/configuration.rb:236:in `block in load'
        from /usr/local/bundle/gems/puma-6.1.1/lib/puma/configuration.rb:236:in `each'
        from /usr/local/bundle/gems/puma-6.1.1/lib/puma/configuration.rb:236:in `load'
        from /usr/local/bundle/gems/puma-6.1.1/lib/puma/launcher.rb:54:in `initialize'
        from /usr/local/bundle/gems/puma-6.1.1/lib/puma/cli.rb:66:in `new'
        from /usr/local/bundle/gems/puma-6.1.1/lib/puma/cli.rb:66:in `initialize'
        from /usr/local/bundle/gems/puma-6.1.1/bin/puma:8:in `new'
        from /usr/local/bundle/gems/puma-6.1.1/bin/puma:8:in `<top (required)>'
        from /usr/local/bundle/bin/puma:25:in `load'
        from /usr/local/bundle/bin/puma:25:in `<main>'
```

This after having successfully run the `db:migrate` and then going to run the command for running the web.

**Comment by jshthornton** [comment]
Might be related to this? https://github.com/puma/puma/issues/2989

**Comment by jshthornton** [comment]
I copied the puma file from the repo and removed the rackup line and copied the file in and it worked. New puma file:
```
workers Integer(ENV['PUMA_WORKERS'] || 3)
threads Integer(ENV['MIN_THREADS']  || 1), Integer(ENV['MAX_THREADS'] || 16)

preload_app!

# rackup DefaultRackup
if ENV['BIND']
  bind ENV['BIND']
else
  port ENV['PORT'] || 3000
end
environment ENV['RACK_ENV'] || 'production'
```

**Comment by ankane** [comment]
Hi @jshthornton, thanks for reporting! Fixed in the commit above.
