### ISSUE TITLE
Problem building the docker image locally.

### ISSUE THREAD

**Issue by Martins6** [ankane/blazer-docker#5]
First, congrats on such a useful open-source project! I wanted to use with a SQL-Server connection so I had to make changes to the Gemfile and build the image locally. But, when I used the following command, it returned an error:

`docker build -t ankane/blazer:latest . `

This is the output that I got:

_Sending build context to Docker daemon  41.98kB
Step 1/14 : FROM ruby:2.7.2-alpine3.11
 ---> 850bf24f9cfe
Step 2/14 : MAINTAINER Andrew Kane <andrew@chartkick.com>
 ---> Using cache
 ---> a37e3c7c4cd9
Step 3/14 : RUN apk add --update ruby-dev build-base   libxml2-dev libxslt-dev pcre-dev libffi-dev   postgresql-dev mysql-dev sqlite-dev git   unixodbc-dev freetds-dev
 ---> Using cache
 ---> ecd394300519
Step 4/14 : RUN gem install bundler
 ---> Using cache
 ---> e3e935067b81
Step 5/14 : ENV INSTALL_PATH /app
 ---> Using cache
 ---> e1f9900a8e23
Step 6/14 : RUN mkdir -p $INSTALL_PATH
 ---> Using cache
 ---> e648810e12de
Step 7/14 : WORKDIR $INSTALL_PATH
 ---> Using cache
 ---> 4854f854a303
Step 8/14 : COPY Gemfile Gemfile.lock ./
 ---> Using cache
 ---> a00570e86808
Step 9/14 : RUN bundle install --binstubs
 ---> Running in 2cf5d756d6ae
[DEPRECATED] The --binstubs option will be removed in favor of `bundle binstubs --all`
Fetching gem metadata from https://rubygems.org/
Fetching gem metadata from https://rubygems.org/.........
**Your bundle is locked to mimemagic (0.3.5) from rubygems repository
https://rubygems.org/ or installed locally, but that version can no longer be
found in that source. That means the author of mimemagic (0.3.5) has removed it.
You'll need to update your bundle to a version other than mimemagic (0.3.5) that
hasn't been removed in order to install.**
The command '/bin/sh -c bundle install --binstubs' returned a non-zero code: 7_

**Comment by Martins6** [comment]
So in trying to solve I tried to update the Gemfile:

```
COPY Gemfile ./

RUN bundle update --all

RUN bundle install --binstubs
```
And now I got this error:

```
Step 9/15 : RUN bundle update --all
 ---> Running in dae7aaa39ccf
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies..............................................................................
Fetching rake 13.0.3
Installing rake 13.0.3
Fetching minitest 5.14.4
Fetching erubi 1.10.0
Fetching builder 3.2.4
Fetching concurrent-ruby 1.1.8
Fetching zeitwerk 2.4.2
Fetching racc 1.5.2
Fetching crass 1.0.6
Fetching rack 2.2.3
Installing crass 1.0.6
Installing zeitwerk 2.4.2
Installing builder 3.2.4
Installing erubi 1.10.0
Fetching nio4r 2.5.7
Fetching websocket-extensions 0.1.5
Installing minitest 5.14.4
Fetching marcel 1.0.1
Fetching mini_mime 1.0.3
Fetching activerecord-sqlserver-adapter 2.3.8
Installing rack 2.2.3
Installing concurrent-ruby 1.1.8
Installing racc 1.5.2 with native extensions
Fetching pg 1.2.3
Installing websocket-extensions 0.1.5
Fetching public_suffix 4.0.6
Installing mini_mime 1.0.3
Installing marcel 1.0.1
Fetching aws-eventstream 1.1.1
Fetching aws-partitions 1.456.0
Fetching jmespath 1.4.0
Installing nio4r 2.5.7 with native extensions
Installing aws-eventstream 1.1.1
Installing activerecord-sqlserver-adapter 2.3.8
Installing pg 1.2.3 with native extensions
Installing public_suffix 4.0.6
Installing jmespath 1.4.0
Installing aws-partitions 1.456.0
Using bundler 2.2.17
Fetching chartkick 4.0.4
Fetching thor 1.1.0
Fetching method_source 1.0.0
Fetching errbase 0.2.1
Installing errbase 0.2.1
Installing method_source 1.0.0
Installing thor 1.1.0
Installing chartkick 4.0.4
Fetching bson 4.12.0
Fetching ione 1.2.4
Fetching declarative 0.0.20
Fetching drill-sergeant 0.1.3
Fetching multipart-post 2.1.1
Fetching multi_json 1.15.0
Fetching ffi 1.15.0
Fetching jwt 2.2.3
Installing drill-sergeant 0.1.3
Fetching memoist 0.16.2
Installing declarative 0.0.20
Installing multipart-post 2.1.1
Installing ione 1.2.4
Installing multi_json 1.15.0
Installing jwt 2.2.3
Fetching os 1.1.1
Fetching httpclient 2.8.3
Installing bson 4.12.0 with native extensions
Fetching trailblazer-option 0.1.1
Fetching uber 0.1.0
Fetching retriable 3.1.2
Installing memoist 0.16.2
Installing ffi 1.15.0 with native extensions
Installing os 1.1.1
Installing trailblazer-option 0.1.1
Installing uber 0.1.0
Installing retriable 3.1.2
Installing httpclient 2.8.3
Fetching thrift 0.14.1
Fetching google-cloud-errors 1.1.0
Fetching webrick 1.7.0
Fetching rexml 3.2.5
Fetching hashie 4.1.0
Fetching ignite-client 0.1.1
Installing google-cloud-errors 1.1.0
Installing ignite-client 0.1.1
Installing rexml 3.2.5
Installing thrift 0.14.1 with native extensions
Installing webrick 1.7.0
Installing hashie 4.1.0
Fetching json 2.5.1
Fetching msgpack 1.4.2
Fetching mysql2 0.5.3
Fetching net_tcp_client 2.2.0
Fetching tiny_tds 2.1.4
Fetching sqlite3 1.4.2
Installing net_tcp_client 2.2.0
Installing mysql2 0.5.3 with native extensions
Installing tiny_tds 2.1.4 with native extensions
Installing sqlite3 1.4.2 with native extensions
Installing msgpack 1.4.2 with native extensions
Installing json 2.5.1 with native extensions
Fetching rack-test 1.1.0
Fetching websocket-driver 0.7.3
Installing websocket-driver 0.7.3 with native extensions
Installing rack-test 1.1.0
Fetching mail 2.7.1
Fetching i18n 1.8.10
Fetching sprockets 4.0.2
Fetching tzinfo 2.0.4
Fetching aws-sigv4 1.2.3
Installing aws-sigv4 1.2.3
Installing i18n 1.8.10
Installing sprockets 4.0.2
Installing tzinfo 2.0.4
Installing mail 2.7.1
Fetching nokogiri 1.11.4 (x86_64-linux)
Fetching addressable 2.7.0
Fetching puma 5.3.1
Fetching faraday 0.17.4
Fetching safely_block 0.3.0
Fetching cassandra-driver 3.2.5
Fetching elasticsearch-api 7.5.0
Fetching representable 3.1.1
Installing safely_block 0.3.0
Fetching mongo 2.14.0
Installing faraday 0.17.4
Installing addressable 2.7.0
Fetching ethon 0.14.0
Installing elasticsearch-api 7.5.0
Installing representable 3.1.1
Fetching hexspace 0.1.1
Installing cassandra-driver 3.2.5 with native extensions
Installing puma 5.3.1 with native extensions
Fetching aws-sdk-core 3.114.0
Installing ethon 0.14.0
Installing hexspace 0.1.1
Installing nokogiri 1.11.4 (x86_64-linux)
Installing mongo 2.14.0
Installing aws-sdk-core 3.114.0
Fetching activesupport 6.1.3.2
Fetching faraday_middleware 0.12.2
Fetching tzinfo-data 1.2021.1
Fetching elasticsearch-transport 7.5.0
Fetching signet 0.15.0
Fetching google-cloud-env 1.5.0
Fetching elasticsearch-xpack 7.12.0
Fetching typhoeus 1.4.0
Installing google-cloud-env 1.5.0
Installing faraday_middleware 0.12.2
Fetching loofah 2.9.1
Installing elasticsearch-transport 7.5.0
Fetching aws-sdk-athena 1.37.0
Installing signet 0.15.0
Installing elasticsearch-xpack 7.12.0
Installing activesupport 6.1.3.2
Fetching aws-sdk-glue 1.87.0
Fetching google-cloud-core 1.6.0
Installing typhoeus 1.4.0
Installing tzinfo-data 1.2021.1
Installing loofah 2.9.1
Fetching faraday_middleware-multi_json 0.0.6
Fetching presto-client 0.6.5
Installing google-cloud-core 1.6.0
Installing aws-sdk-athena 1.37.0
Fetching restforce 5.0.5
Fetching elasticsearch 7.5.0
Installing aws-sdk-glue 1.87.0
Fetching googleauth 0.16.2
Fetching rails-html-sanitizer 1.3.0
Installing presto-client 0.6.5
Installing faraday_middleware-multi_json 0.0.6
Fetching rails-dom-testing 2.0.3
Fetching globalid 0.4.2
Fetching activemodel 6.1.3.2
Installing restforce 5.0.5
Installing elasticsearch 7.5.0
Fetching neo4j-core 9.0.0
Installing rails-html-sanitizer 1.3.0
Installing googleauth 0.16.2
Installing globalid 0.4.2
Installing rails-dom-testing 2.0.3
Fetching activejob 6.1.3.2
Fetching google-apis-core 0.3.0
Fetching actionview 6.1.3.2
Installing activemodel 6.1.3.2
Installing neo4j-core 9.0.0
Fetching activerecord 6.1.3.2
Installing activejob 6.1.3.2
Installing google-apis-core 0.3.0
Fetching google-apis-bigquery_v2 0.9.0
Installing actionview 6.1.3.2
Fetching actionpack 6.1.3.2
Installing activerecord 6.1.3.2
Installing google-apis-bigquery_v2 0.9.0
Fetching google-cloud-bigquery 1.31.0
Fetching activerecord6-redshift-adapter 1.1.3
Installing actionpack 6.1.3.2
Fetching actioncable 6.1.3.2
Fetching sprockets-rails 3.2.2
Fetching actionmailer 6.1.3.2
Fetching activestorage 6.1.3.2
Fetching railties 6.1.3.2
Installing google-cloud-bigquery 1.31.0
Installing activerecord6-redshift-adapter 1.1.3
Installing sprockets-rails 3.2.2
Installing actionmailer 6.1.3.2
Installing actioncable 6.1.3.2
Installing activestorage 6.1.3.2
Fetching actionmailbox 6.1.3.2
Fetching actiontext 6.1.3.2
Installing railties 6.1.3.2
Installing actiontext 6.1.3.2
Installing actionmailbox 6.1.3.2
Fetching rails 6.1.3.2
Fetching blazer 2.4.2
Installing rails 6.1.3.2
Installing blazer 2.4.2
Bundle updated!
Removing intermediate container dae7aaa39ccf
 ---> 3b1613e7cc9c
Step 10/15 : RUN bundle install --binstubs
 ---> Running in 496f8693719a
[DEPRECATED] The --binstubs option will be removed in favor of `bundle binstubs --all`
Using rake 13.0.3
Using concurrent-ruby 1.1.8
Using i18n 1.8.10
Using minitest 5.14.4
Using tzinfo 2.0.4
Using zeitwerk 2.4.2
Using activesupport 6.1.3.2
Using builder 3.2.4
Using erubi 1.10.0
Using racc 1.5.2
Using nokogiri 1.11.4 (x86_64-linux)
Using rails-dom-testing 2.0.3
Using crass 1.0.6
Using loofah 2.9.1
Using rails-html-sanitizer 1.3.0
Using actionview 6.1.3.2
Using rack 2.2.3
Using rack-test 1.1.0
Using actionpack 6.1.3.2
Using nio4r 2.5.7
Using websocket-extensions 0.1.5
Using websocket-driver 0.7.3
Using actioncable 6.1.3.2
Using globalid 0.4.2
Using activejob 6.1.3.2
Using activemodel 6.1.3.2
Using activerecord 6.1.3.2
Using marcel 1.0.1
Using mini_mime 1.0.3
Using activestorage 6.1.3.2
Using mail 2.7.1
Using actionmailbox 6.1.3.2
Using actionmailer 6.1.3.2
Using actiontext 6.1.3.2
Using activerecord-sqlserver-adapter 2.3.8
Using pg 1.2.3
Using activerecord6-redshift-adapter 1.1.3
Using public_suffix 4.0.6
Using addressable 2.7.0
Using aws-eventstream 1.1.1
Using aws-partitions 1.456.0
Using aws-sigv4 1.2.3
Using jmespath 1.4.0
Using aws-sdk-core 3.114.0
Using aws-sdk-athena 1.37.0
Using aws-sdk-glue 1.87.0
Using chartkick 4.0.4
Using method_source 1.0.0
Using thor 1.1.0
Using railties 6.1.3.2
Using errbase 0.2.1
Using safely_block 0.3.0
Using blazer 2.4.2
Using bson 4.12.0
Using bundler 2.2.17
Using ione 1.2.4
Using cassandra-driver 3.2.5
Using declarative 0.0.20
Using drill-sergeant 0.1.3
Using multi_json 1.15.0
Using elasticsearch-api 7.5.0
Using multipart-post 2.1.1
Using faraday 0.17.4
Using elasticsearch-transport 7.5.0
Using elasticsearch 7.5.0
Using elasticsearch-xpack 7.12.0
Using ffi 1.15.0
Using ethon 0.14.0
Using faraday_middleware 0.12.2
Using faraday_middleware-multi_json 0.0.6
Using jwt 2.2.3
Using memoist 0.16.2
Using os 1.1.1
Using signet 0.15.0
Using googleauth 0.16.2
Using httpclient 2.8.3
Using trailblazer-option 0.1.1
Using uber 0.1.0
Using representable 3.1.1
Using retriable 3.1.2
Using rexml 3.2.5
Using webrick 1.7.0
Using google-apis-core 0.3.0
Using google-apis-bigquery_v2 0.9.0
Using google-cloud-env 1.5.0
Using google-cloud-errors 1.1.0
Using google-cloud-core 1.6.0
Using google-cloud-bigquery 1.31.0
Using hashie 4.1.0
Using thrift 0.14.1
Using hexspace 0.1.1
Using ignite-client 0.1.1
Using json 2.5.1
Using mongo 2.14.0
Using msgpack 1.4.2
Using mysql2 0.5.3
Using net_tcp_client 2.2.0
Using typhoeus 1.4.0
Using neo4j-core 9.0.0
Using presto-client 0.6.5
Using puma 5.3.1
Using sprockets 4.0.2
Using sprockets-rails 3.2.2
Using rails 6.1.3.2
Using restforce 5.0.5
Using sqlite3 1.4.2
Using tiny_tds 2.1.4
Using tzinfo-data 1.2021.1
Bundle complete! 23 Gemfile dependencies, 108 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
Removing intermediate container 496f8693719a
 ---> 6d25bbfef2cf
Step 11/15 : COPY . .
 ---> b968f95dc15e
Step 12/15 : RUN bundle exec rake RAILS_ENV=production DATABASE_URL=postgresql://user:pass@127.0.0.1/dbname SECRET_TOKEN=dummytoken assets:precompile
 ---> Running in d6bb9f609502
bundler: failed to load command: rake (/usr/local/bundle/bin/rake)
/usr/local/bundle/gems/bundler-2.2.17/lib/bundler/spec_set.rb:95:in `block in materialize': Could not find i18n-1.8.8 in any of the sources (Bundler::GemNotFound)
        from /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/spec_set.rb:90:in `map!'
        from /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/spec_set.rb:90:in `materialize'
        from /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/definition.rb:183:in `specs'
        from /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/definition.rb:253:in `specs_for'
        from /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/definition.rb:235:in `requested_specs'
        from /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/runtime.rb:91:in `block in definition_method'
        from /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/runtime.rb:20:in `setup'
        from /usr/local/bundle/gems/bundler-2.2.17/lib/bundler.rb:148:in `setup'
        from /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/setup.rb:20:in `block in <top (required)>'
        from /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/ui/shell.rb:136:in `with_level'
        from /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/ui/shell.rb:88:in `silence'
        from /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/setup.rb:20:in `<top (required)>'
        from /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/cli/exec.rb:61:in `require_relative'
        from /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/cli/exec.rb:61:in `kernel_load'
        from /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/cli/exec.rb:28:in `run'
        from /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/cli.rb:494:in `exec'
        from /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/cli.rb:30:in `dispatch'
        from /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/cli.rb:24:in `start'
        from /usr/local/bundle/gems/bundler-2.2.17/exe/bundle:49:in `block in <top (required)>'
        from /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
        from /usr/local/bundle/gems/bundler-2.2.17/exe/bundle:37:in `<top (required)>'
        from /usr/local/bundle/bin/bundle:23:in `load'
        from /usr/local/bundle/bin/bundle:23:in `<main>'
The command '/bin/sh -c bundle exec rake RAILS_ENV=production DATABASE_URL=postgresql://user:pass@127.0.0.1/dbname SECRET_TOKEN=dummytoken assets:precompile' returned a non-zero code: 1
```

**Comment by ankane** [comment]
Hey @Martins6, thanks for reporting! Just pushed an update that should fix the build errors.

**Comment by Martins6** [comment]
Thanks so much! It worked perfectly. Again, congrats for such a nice project, mate!
